//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDoan
    {
        public int Ma_CTDoan { get; set; }
        public Nullable<int> MaDoan { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual Doan Doan { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
