//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Doan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doan()
        {
            this.ChiTietDoans = new HashSet<ChiTietDoan>();
        }
    
        public int MaDoan { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập tên đòan")]
        [Display(Name = "Tên đoàn")]
        public string TenDoan { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập nội dung")]
        [Display(Name = "Nội dung")]
        public string NoiDung { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập ngày đi")]
        [Display(Name = "Ngày đi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayDi { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập ngày kết thúc")]
        [Display(Name = "Ngày kết thúc")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<int> MaTour { get; set; }

        [Display(Name = "Tình trạng")]
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDoan> ChiTietDoans { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
