//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.ChiTietDoans = new HashSet<ChiTietDoan>();
            this.QuaTrinhTours = new HashSet<QuaTrinhTour>();
        }
    
        public int MaKH { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập họ tên")]
        [Display(Name = "Họ và tên")]
        public string TenKH { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập số CMND")]
        [RegularExpression(@"(^\d{9}$)", ErrorMessage = "Yêu cầu nhập đúng số CMND")]
        [Display(Name = "Số CMND")]
        public string CMND { get; set; }

        [Required(ErrorMessage = "Yêu cầu nhập địa chỉ")]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }

        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }

        [RegularExpression(@"(^\d{11}|\d{10}$)", ErrorMessage = "Yêu cầu nhập đúng số điện thoại")]
        [Required(ErrorMessage = "Yêu cầu nhập số điện thoại")]
        [Display(Name = "Số điện thoại")]
        public string SoDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDoan> ChiTietDoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhTour> QuaTrinhTours { get; set; }
    }
}
