//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class QuaTrinhTour
    {
        public int Ma { get; set; }
        public Nullable<int> MaKH { get; set; }

        [Display(Name = "Tên tour")]
        public string TenTour { get; set; }

        [Display(Name = "Thông tin tour")]
        public string ThongTinTour { get; set; }

        [Display(Name = "Giá tour")]
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> GiaTour { get; set; }

        [Display(Name = "Ngày đi")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayDi { get; set; }

        [Display(Name = "Ngày kết thúc")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
